Fixed #21, no more wonky process detection
Now utilizing persistent process counter saved to file

diff --git a/nvx b/nvx
--- a/nvx
+++ b/nvx
@@ -30,13 +30,6 @@ function ps_nvidia {
     lsof /dev/nvidia* 2>/dev/null | awk '{ if (NR>1) pids[$2" "$1]++ } END { for (pid in pids) { print pid } }'
 }
 
-# Print which processes are a nvx start instance.
-function ps_nvx {
-    PS="$(ps aux)"
-    # sleep 1
-    echo "$PS" | awk '/nvx start/ { cmd=""; for (i = 5 ; i <= NF ; i++) cmd = cmd " " $i; print $0 }'
-}
-
 ### setup functions ###
 
 # Kill processes that are accessing nvidia device files.
@@ -119,38 +112,80 @@ function load_modules {
     done
 }
 
-### execution functions ###
+### persistent counter functions ###
 
-LOCK=/tmp/nvx.lock
+COUNTER_FILE="/tmp/nvidia_processes"
+
+function counter_check_and_create {
+    # create counter if it doesn't exist
+    if [ ! -f ${COUNTER_FILE} ]; then
+        # no file
+        echo 0 > ${COUNTER_FILE}
+    fi
+}
+
+function counter_get_value {
+    counter_check_and_create
+
+    c=$(cat ${COUNTER_FILE})
+
+    # returns as exit code in $?
+    return $c
+}
+
+function counter_incr {
+    counter_get_value
+    c=$?
+
+    c=$(($c+1))
+    echo $c > ${COUNTER_FILE}
+}
+
+function counter_decr {
+    counter_get_value
+    c=$?
+
+    c=$(($c-1))
+    echo $c > ${COUNTER_FILE}
+}
+
+function counter_print {
+    counter_get_value
+    echo "running processes: $?"
+}
+
+### execution functions ###
 
 # Check if there are any other nvx start instances running and start the gpu if not.
 function start {
-    exec 3>"$LOCK"
-    flock -x 3
-    # TODO investigate
-    # when ps_nvx is piped to wc -l directly, it counts one extra line because a subprocess is spawn.
-    # I do not know where that process come from. I found out that does not happen if I write it to a file.
-    ps_nvx >"$LOCK"
-    PS=$(cat "$LOCK" | wc -l)
-    if [ "$PS" -le 1 ]; then
+
+    # before program actually starts
+    counter_get_value
+    val=$?
+
+    if [ "$val" -eq 0 ]; then
+        # no processes running
         turn_on
         load_modules
     fi
-    flock -u 3
+
+    counter_incr
 }
 
 # Check if there are any other nvx start instances running and stop the gpu if not.
 function stop {
-    exec 3>"$LOCK"
-    flock -x 3
-    ps_nvx >"$LOCK"
-    PS=$(cat "$LOCK" | wc -l)
-    if [ "$PS" -le 1 ]; then
+
+    # after program actually ends
+    counter_decr
+    counter_get_value
+    val=$?
+
+    if [ "$val" -eq 0 ]; then
+        # no process running
         ps_nvidia_kill
         unload_modules
         turn_off
     fi
-    flock -u 3
 }
 
 case "$1" in
@@ -158,7 +193,7 @@ case "$1" in
 dev) devices | jq ;;
 status) status ;;
 ps) ps_nvidia ;;
-psx) ps_nvx ;;
+process) counter_print ;;
 #
 kill) ps_nvidia_kill ;;
 off)
@@ -221,8 +256,8 @@ Usage: $0 [start|on|off|off-boot|off-kill|status|ps|psx|kill|dev]
     ps
         Print the processes using the gpu.
 
-    psx
-        Print 'nvx start' processes.
+    process
+        Print how many processes are using the gpu.
 
     kill
         Attempts to kill all processes using the gpu.
